source "https://rubygems.org"

gem 'jekyll', '~> 4'

group :jekyll_plugins do
  gem 'jekyll_picture_tag', :github => 'rbuchberger/jekyll_picture_tag', :branch => 'master'
  gem 'jekyll-last-modified-at', '~> 1.2', '>= 1.2.1'
  gem 'rmagick', '~> 4.1.2'
end

group :development do
  gem 'pry'
  gem 'awesome_print'
end